# Default values for spotinst-kubernetes-cluster-controller.

# Default namespace.
namespace: kube-system

# Spotinst configuration.
spotinst:
  # Credentials, see: https://api.spotinst.com/spotinst-api/administration/create-an-api-token.
  token: ""
  account: ""

  # Configuration.
  clusterIdentifier: ""
  baseUrl: ""
  proxyUrl: ""
  disableAutoUpdate: false
  enableCsrApproval: false

# Metrics Server configuration.
metrics-server:
  deployChart: true
  args:
  - --logtostderr
  # enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  #  - --kubelet-insecure-tls

# Resource requests and limits.
resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Image.
image:
  repository: spotinst/kubernetes-cluster-controller
  pullPolicy: Always

dnsPolicy: ClusterFirst

tolerations:
- key: node.kubernetes.io/not-ready
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node.kubernetes.io/unreachable
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node-role.kubernetes.io/master
  operator: Exists

nodeAffinity:
  matchKey: node-role.kubernetes.io/master
