# Default values for spotinst-kubernetes-cluster-controller.

# Spotinst configuration.
spotinst:
  # Credentials, see: https://api.spotinst.com/spotinst-api/administration/create-an-api-token.
  token: ""
  account: ""

  # Configuration.
  clusterIdentifier: ""
  proxyUrl: ""
  disableAutoUpdate: false
  
# Metrics Server configuration.
metrics-server:
  deployChart: true
  args:
  - --logtostderr
  # enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  #  - --kubelet-insecure-tls

# Resource requests and limits.
resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
